donshoppy/app/urls.py
from django.urls import path
from .views import home,sobreNosotros,contacto,producto,zapatillas,catalogo,ropas,mochilas,agregar_producto,listar_producto,modificar_producto,eliminar_producto,registro,abarrotes,servicios,herramientas,outdoors,about

urlpatterns = [
    path('', home,name="home"),
    path('sobreNosotros/',sobreNosotros,name="sobreNosotros"),
    path('contacto/',contacto,name="contacto"),
    path('producto/',producto,name="producto"),
    path('zapatillas/',zapatillas,name="zapatillas"),
    path('mochilas/',mochilas,name="mochilas"),
    path('abarrotes/',abarrotes,name="abarrotes"),
    path('servicios/',servicios,name="servicios"),
    path('ropas/',ropas,name="ropas"),
    path('herramientas/',herramientas,name="herramientas"),
    path('outdoors/',outdoors,name="outdoors"),
    path('catalogo/',catalogo,name="catalogo"),
    path('agregar_producto/',agregar_producto,name="agregar_producto"),
    path('listar_producto/',listar_producto,name="listar_producto"),
    path('modificar_producto/<id>/',modificar_producto,name="modificar_producto"),
    path('eliminar_producto/<id>/',eliminar_producto,name="eliminar_producto"),
    path('registro/',registro,name="registro"),
    path('about/',about,name="about"),
]

donshoppy/donshoppy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donshoppy/app/models.py
from django.db import models

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)
    contact=models.IntegerField()
    numerodpto=models.IntegerField()

    def __str__(self):
        return self.nombre

class Zapatilla(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)

    def __str__(self):
        return self.nombre

class Ropa(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Abarrote(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Herramienta(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre

class Outdoor(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre

class Servicio(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Mochila(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Contacto(models.Model):
    nombre=models.CharField(max_length=50)
    correo=models.EmailField()
    comentario=models.TextField()

    def __str__(self):
        return self.nombre

donshoppy/app/templates/app/abarrotes.html
{%extends 'app/base.html'%}

{%block contenido%}

<div id="main">
    {%load humanize%}
    {%for p in abarrotes %}
	<!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            {%if p.imagen%}
                            <img class="w-100 h-100" src="{{p.imagen.url}}" alt="Image">
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{p.nombre | title}}</h3>
                    <h3 class="font-weight-semi-bold mb-4">${{p.precio | intcomma}}</h3>
                    <p class="mb-4">{{p.marca | capfirst}}</p>
					<p class="mb-4">Incluye:</p>
					<p class="mb-4">Caja</p>
					<p class="mb-4">Favor comunicarse con el Depto 405</p>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Descripcion</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Descripcion de Producto</h4>
                            <p>{{p.descripcion}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}


{%endblock%}

donshoppy/app/templates/app/about.html
{%extends 'app/base.html'%}

{%block contenido%}
<div id="main">


    <article class="post">
        <header>
            <div class="title">
                <h2><a href="#">Politicas y Privacidad</a></h2>
            </div>
        </header>
            <h2>1. Introducción</h2>
                
                <br><p>1.1. Bienvenido al sitio web Don Shoppy. Estas políticas de uso establecen los términos y condiciones que rigen tu acceso y uso de nuestro sitio web. Al acceder y utilizar el sitio, 
                aceptas cumplir con estas políticas de uso en su totalidad. Si no estás de acuerdo con alguna parte de estas políticas, te recomendamos que no utilices nuestro sitio.</p>
                
            <h2><br>2. Seguridad de la Información</h2>
                
                <br><p>2.1. Responsabilidad del Usuario: Eres responsable de mantener la confidencialidad de tus credenciales de acceso al sitio web. 
                    No compartas tu nombre de usuario ni tu contraseña con terceros y notifícanos de inmediato cualquier uso no autorizado de tu cuenta.</p>
                
                <p>2.2. Protección de Datos Personales: Respetamos tu privacidad y nos comprometemos a proteger tus datos personales. 
                    Recopilamos, utilizamos y almacenamos tus datos de acuerdo con nuestras políticas de privacidad, las cuales puedes revisar en nuestra página de políticas de privacidad.</p>
                
                <p>2.3. Uso de Datos de los Usuarios: Nos comprometemos a utilizar los datos personales de los usuarios solo con fines relacionados con la operación del sitio web y la prestación de servicios. 
                    No compartiremos tus datos con terceros sin tu consentimiento expreso, a menos que sea requerido por la ley.</p>
                
            <h2><br>3. Responsabilidad del Usuario</h2>
                
                <br><p>Contenido Generado por el Usuario: Si publicas contenido en nuestro sitio web, como comentarios, 
                    opiniones o reseñas, eres el único responsable de dicho contenido. No se permite publicar contenido difamatorio, obsceno, ilegal o que infrinja los derechos de propiedad intelectual de terceros.</p>
                
                <p>3.2. Cumplimiento de las Leyes: Al utilizar nuestro sitio web, te comprometes a cumplir con todas las leyes y regulaciones aplicables. No utilices nuestro sitio para actividades ilegales o fraudulentas.</p>
                
                <p>3.3. Conducta Adecuada: No toleramos el acoso, la discriminación, el lenguaje ofensivo o cualquier forma de comportamiento inapropiado en nuestro sitio web. Nos reservamos el derecho de tomar medidas, 
                    incluida la suspensión o eliminación de cuentas, ante cualquier violación de esta política.</p>
                
            <h2><br>4. Propiedad Intelectual</h2>
                
                <br><p>Derechos de Autor: Respetamos los derechos de autor y esperamos que nuestros usuarios también lo hagan. 
                    No se permite la publicación de contenido protegido por derechos de autor sin el permiso expreso del propietario. Si crees que se ha infringido tu derecho de autor, contáctanos de inmediato.</p>
                
                <p>4.2. Licencia de Uso: Al publicar contenido en nuestro sitio web, nos otorgas una licencia no exclusiva, 
                    mundial, perpetua y libre de regalías para utilizar, reproducir, modificar, adaptar y distribuir dicho contenido con fines relacionados con la operación del sitio web.</p>
                                            
    </article>
    
    <article class="post">
        <header>
            <div class="title">
                <h2><br><a href="#">Descargo de Responsabilidad</a></h2>
            </div>
        </header>

        <br><h2>1. Aceptación de los términos:</h2>
        <br><p>Al utilizar este producto/servicio/sitio web, el usuario acepta los términos y condiciones establecidos en el descargo de responsabilidad.</p>
            
        <h2><br>2. Información general:</h2> 
        <br><p>Toda la información proporcionada tiene únicamente fines informativos y no debe considerarse asesoramiento legal, médico, financiero u otro tipo de asesoramiento profesional.</p>
            
        <h2><br>3. Limitación de responsabilidad:</h2>
        <br><p> La empresa/individuo no se hace responsable de ningún daño directo, indirecto, incidental, consecuente o especial que pueda surgir del uso o la incapacidad de utilizar el producto/servicio/información proporcionada.</p>
            
        <h2><br>4. Uso bajo responsabilidad del usuario:</h2> 
        <br><p> El usuario asume toda la responsabilidad y riesgo por el uso del producto/servicio/información. La empresa/individuo no garantiza la exactitud, integridad o actualidad de la información proporcionada.</p>
            
        <h2><br>5. Exclusión de garantías:</h2>
        <br><p> La empresa/individuo renuncia a cualquier garantía, expresa o implícita, incluyendo, pero no limitándose a, garantías de comerciabilidad, idoneidad para un propósito particular y no infracción.</p>
            
        <h2><br>6. Enlaces a terceros:</h2> 
        <br><p>Este producto/servicio/sitio web puede contener enlaces a sitios web de terceros. La empresa/individuo no se hace responsable del contenido, la precisión o las prácticas de privacidad de dichos sitios.</p>
            
        <h2><br>7. Cambios en la política:</h2> 
        <br><p>La empresa/individuo se reserva el derecho de modificar o actualizar esta política de descargo de responsabilidad en cualquier momento. Se recomienda revisar periódicamente la política para estar al tanto de cualquier cambio.</p>
            

        <br><ul>
            <li><a href="#">La empresa no se hace cargo de robos o estafas</a></li>
            <li><a href="#">No realice transferencias sin antes recibir el producto</a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
         </ul>
    </article>
</div>
<script src="app/js/jquery.min.js"></script>
<script src="app/js/browser.min.js"></script>
<script src="app/js/breakpoints.min.js"></script>
<script src="app/js/util.js"></script>
<script src="app/js/main.js"></script>
{%endblock%}

donshoppy/app/templates/app/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Home</title>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		{%load static%}
		<link rel="stylesheet" href="{% static 'app/css/main.css'%} ">
		<!-- bootstrap css -->
		<link rel="stylesheet" type="text/css" href="{% static 'app/css/bootstrap.min.css'%}">
		<!-- style css -->
		<link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css'%}">
		<!-- Responsive-->
		<link rel="stylesheet" href="{% static 'app/css/responsive.css'%}">
		<!-- fevicon -->
		<link rel="icon" href="{%static 'app/img/fevicon.png'%}" type="{%static 'app/img/gif'%}" />
		<!-- font css -->
		<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap" rel="stylesheet">
		<!-- Scrollbar Custom CSS -->
		<link rel="stylesheet" href="{% static 'app/css/jquery.mCustomScrollbar.min.css'%}">
		<!-- Tweaks for older IEs-->
		<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

		
	</head>
	<body class="is-preload">
		<div class="contenido">
			
			{%block contenido%}
			
			{%endblock%}
		</div>


		<div id="wrapper">

			<header id="header">
				<h1><a href="{%url 'home'%}">Don Shoppy</a></h1>
				<nav class="links">
					<ul>
						<li><a href="{%url 'contacto'%}">Contacto</a></li>
						<li><a href="{%url 'sobreNosotros'%}">Sobre Nosotros</a></li>
						<li><a href="{%url 'listar_producto'%}">Publicaciones</a></li>
						
						{%if user.is_authenticated%}
							{%if perms.app.add_producto%}
								<li><a href="{%url 'agregar_producto'%}">Publicar producto</a></li>
							{% endif%}
							<li>
								<a href="{%url 'logout' %}">cerrar sesion</a>
								<li><a href="{%url 'listar_producto'%}">Publicaciones</a></li>
							</li>
						{%else%}
							<li>
								<a href="{%url 'logout' %}">inciar sesion</a>
							</li>
						{%endif%}
					</ul>
				</nav>
				<nav class="main">
					<ul>
						<li class="search">
							<a class="fa-search" href="#search">Buscar</a>
							<form id="search" method="get" action="#">
								<input type="text" name="query" placeholder="Search" />
							</form>
						</li>
						<li class="menu">
							<a class="fa-bars" href="ingreso.html">Ingresar</a>
						</li>
					</ul>
				</nav>
			</header>
			</section>
		</div>

  		<!-- copyright section start -->
		<div class="copyright_section">
			<div class="container">
			   <div class="row">
				  <div class="col-lg-6 col-sm-12">
					 <p class="copyright_text">2020 All Rights Reserved. Design by <a href="https://html.design">Free Html Templates</a></p>
				  </div>
				  <div class="col-lg-6 col-sm-12">
					 <div class="footer_social_icon">
						<ul>
						   <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						   <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						   <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						   <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						</ul>
					 </div>
				  </div>
			   </div>
			</div>
		 </div>
		<!-- copyright section end -->

		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/browser.min.js"></script>
		<script src="assets/js/breakpoints.min.js"></script>
		<script src="assets/js/util.js"></script>
		<script src="assets/js/main.js"></script>
		<!-- copyright section end -->
      	<!-- Javascript files-->
      	<script src="assets/js/jquery.min.js"></script>
      	<script src="assets/js/popper.min.js"></script>
      	<script src="assets/js/bootstrap.bundle.min.js"></script>
      	<script src="assets/js/jquery-3.0.0.min.js"></script>
      	<script src="assets/js/plugin.js"></script>
      	<!-- sidebar -->
      	<script src="assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
      	<script src="assets/js/custom.js"></script>

		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
		

		{%if messages%}
		 	{%for m in messages%}
		 		<script>
					Swal.fire({
						"title":"Felicitaciones",
						"text":"{{m}}"
					})
				</script>
			{% endfor%}
		{%endif%}
	</body>
</html>

donshoppy/app/templates/app/contacto.html
{%extends 'app/base.html'%}

{%block contenido%}
<div id="wrapper">
  

        <div class="container-fluid bg-grey">
            <h2 class="text-center">Contacto</h2>
            <div class="row">
              <div class="col-sm-5">
                <p>Las consultas se responderan en las proximas 24 Horas</p>
                <p><span class="glyphicon glyphicon-map-marker"></span> Santiago Centro</p>
                <p><span class="glyphicon glyphicon-phone"></span> +56912345678</p>
                <p><span class="glyphicon glyphicon-envelope"></span> contacto@shoppy.com</p>
              </div>
              <div class="col-sm-7">
                <form action="" class="formulario_contacto" method="post">
                {% csrf_token %}
                {{ form }}
                
                <div class="row">
                  <div class="col-sm-12 form-group">
                    <button class="btn btn-default pull-right" type="submit">Enviar</button>
                    
                  </div>
                </div>
                </form>
              </div>

            </div>
          </div>
          
</div>
<script src="app/js/jquery.min.js"></script>
<script src="app/js/browser.min.js"></script>
<script src="app/js/breakpoints.min.js"></script>
<script src="app/js/util.js"></script>
<script src="app/js/main.js"></script>


{%endblock%}

donshoppy/app/templates/app/herramientas.html
{%extends 'app/base.html'%}

{%block contenido%}

<div id="main">
    {%load humanize%}
    {%for p in herramientas %}
	<!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            {%if p.imagen%}
                            <img class="w-100 h-100" src="{{p.imagen.url}}" alt="Image">
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{p.nombre | title}}</h3>
                    <h3 class="font-weight-semi-bold mb-4">${{p.precio | intcomma}}</h3>
                    <p class="mb-4">{{p.marca | capfirst}}</p>
					<p class="mb-4">Incluye:</p>
					<p class="mb-4">Caja</p>
					<p class="mb-4">Favor comunicarse con el Depto 405</p>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Descripcion</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Descripcion de Producto</h4>
                            <p>{{p.descripcion}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}


{%endblock%}

donshoppy/app/templates/app/mochilas.html
{%extends 'app/base.html'%}

{%block contenido%}

<div id="main">
    {%load humanize%}
    {%for p in mochilas %}
	<!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            {%if p.imagen%}
                            <img class="w-100 h-100" src="{{p.imagen.url}}" alt="Image">
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{p.nombre | title}}</h3>
                    <h3 class="font-weight-semi-bold mb-4">${{p.precio | intcomma}}</h3>
                    <p class="mb-4">{{p.marca | capfirst}}</p>
					<p class="mb-4">Incluye:</p>
					<p class="mb-4">Caja</p>
					<p class="mb-4">Favor comunicarse con el Depto 405</p>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Descripcion</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Descripcion de Producto</h4>
                            <p>{{p.descripcion}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}


{%endblock%}

donshoppy/app/templates/app/outdoors.html
{%extends 'app/base.html'%}

{%block contenido%}

<div id="main">
    {%load humanize%}
    {%for p in outdoors %}
	<!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            {%if p.imagen%}
                            <img class="w-100 h-100" src="{{p.imagen.url}}" alt="Image">
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{p.nombre | title}}</h3>
                    <h3 class="font-weight-semi-bold mb-4">${{p.precio | intcomma}}</h3>
                    <p class="mb-4">{{p.marca | capfirst}}</p>
					<p class="mb-4">Incluye:</p>
					<p class="mb-4">Caja</p>
					<p class="mb-4">Favor comunicarse con el Depto 405</p>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Descripcion</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Descripcion de Producto</h4>
                            <p>{{p.descripcion}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}


{%endblock%}

donshoppy/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if productos.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ productos.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != productos.number and paginator.num_pages > 7 %} 
                {% if productos.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ productos.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == productos.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == productos.number %}
            <li class="page-item {% if page == productos.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if productos.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ productos.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if productos.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ productos.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if productos.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ productos.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}