donshoppy/app/urls.py
from django.urls import path
from .views import home,sobreNosotros,contacto,producto,zapatillas,catalogo,ropas,mochilas,agregar_producto,listar_producto,modificar_producto,eliminar_producto,registro,abarrotes,servicios,herramientas,outdoors,about

urlpatterns = [
    path('', home,name="home"),
    path('sobreNosotros/',sobreNosotros,name="sobreNosotros"),
    path('contacto/',contacto,name="contacto"),
    path('producto/',producto,name="producto"),
    path('zapatillas/',zapatillas,name="zapatillas"),
    path('mochilas/',mochilas,name="mochilas"),
    path('abarrotes/',abarrotes,name="abarrotes"),
    path('servicios/',servicios,name="servicios"),
    path('ropas/',ropas,name="ropas"),
    path('herramientas/',herramientas,name="herramientas"),
    path('outdoors/',outdoors,name="outdoors"),
    path('catalogo/',catalogo,name="catalogo"),
    path('agregar_producto/',agregar_producto,name="agregar_producto"),
    path('listar_producto/',listar_producto,name="listar_producto"),
    path('modificar_producto/<id>/',modificar_producto,name="modificar_producto"),
    path('eliminar_producto/<id>/',eliminar_producto,name="eliminar_producto"),
    path('registro/',registro,name="registro"),
    path('about/',about,name="about"),
]

donshoppy/donshoppy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donshoppy/app/models.py
from django.db import models

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)
    contact=models.IntegerField()
    numerodpto=models.IntegerField()

    def __str__(self):
        return self.nombre

class Zapatilla(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)

    def __str__(self):
        return self.nombre

class Ropa(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Abarrote(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Herramienta(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre

class Outdoor(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre

class Servicio(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Mochila(models.Model):
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField()
    descripcion=models.TextField()
    nuevo=models.BooleanField()
    marca=models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to="productos",null=True)


    def __str__(self):
        return self.nombre
    
class Contacto(models.Model):
    nombre=models.CharField(max_length=50)
    correo=models.EmailField()
    comentario=models.TextField()

    def __str__(self):
        return self.nombre

donshoppy/app/templates/app/producto/agregar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {%load static%}
    
    <title>Agregar</title>
</head>
<body>
    {%if messages%}
        {%for m in messages%}
            <script>
                Swal.fire({
                    "title":"Felicitaciones",
                    "text":"{{m}}",
                    "icon":"success"
                })
            </script>
        {%endfor%}
    {% endif %}
    {% load crispy_forms_tags %}
    <button class="btn"><a href="{%url 'home'%}">Volver a incio</a></button>
    <div class="card">
        <div class="card-body">
            <div class="col-12 col-md-6 offset-md-3">
                <h2>Publicar producto</h2>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div class="d-flex justify-content-center">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>

donshoppy/app/templates/app/producto/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {%load static%}
    
    <title>Listar</title>
</head>
<body>
    {% load crispy_forms_tags %}
    {% load humanize%}
    <button class="btn"><a href="{%url 'home'%}">Volver a incio</a></button>
    <div class="card">
        <div class="card-body">
            <h2>listado de productos</h2>
        </div>
    </div>
    <table class="table table-striped table-hover table-responsive-small">
        <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Marca</th>
        </tr>
        {% for p in productos %}
        <tr>
            <td>{{p.nombre | title}}</td>
            <td>{{p.precio | intcomma}}</td>
            <td>{{p.marca | title}}</td>
            <td>
                {% if perms.app.change_producto %}
                    <button class="btn btn-primary"><a href="{% url 'modificar_producto' p.id%}" style="color: aliceblue;">Modificar</a></button>
                {%endif%}
                {% if perms.app.delete_producto %}
                    <button class="btn btn-danger"><a href="{% url 'eliminar_producto' p.id%}" style="color: aliceblue;">Eliminar</a></button>
                {%endif%}
            </td>
        </tr>
        {% endfor %}
    </table>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {%if messages%}
        {%for m in messages%}
            <script>
                Swal.fire({
                    "title":"Felicitaciones",
                    "text":"{{m}}",
                    "icon":"success"
                })
            </script>
        {%endfor%}
    {% endif %}
    <div>
        {%include 'app/paginator.html'%}
    </div>
</body>
</html>

donshoppy/app/templates/app/producto/modificar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {%load static%}
    
    <title>Modificar</title>
</head>
<body>
    {% load crispy_forms_tags %}
    <button class="btn"><a href="{%url 'home'%}">Volver a incio</a></button>
    <button class="btn"><a href="{%url 'listar_producto'%}">Volver a listado</a></button>
    <div class="card">
        <div class="card-body">
            <div class="col-12 col-md-6 offset-md-3">
                <h2>Editar producto</h2>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div class="d-flex justify-content-center">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>
</html>